dotnet user-secrets set "Kestrel:Certificates:Default:Password" "password"
dotnet user-secrets set "ConnectionStrings:DefaultDatabase" "Host=postgres;Database=identity-development;Username=postgres;Password=postgres;Port=5432"
dotnet user-secrets set "RabbitMQ:Username" "guest"
dotnet user-secrets set "RabbitMQ:Password" "guest"
dotnet user-secrets set "Email:Address" "cowboysteamts@gmail.com"
dotnet user-secrets remove "Kestrel:Certificates:Default:Password" -p ../AlbyOnContainers.IdentityServer.csproj
dotnet user-secrets remove "ConnectionStrings:DefaultDatabase"
dotnet user-secrets remove "RabbitMQ:Username"
dotnet user-secrets remove "RabbitMQ:Password"
dotnet user-secrets remove "Email:Address"